# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -XX:+UseG1GC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=false

# Android specific flags
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin flags
kotlin.incremental=false
kotlin.code.style=official
